# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: InsideTest
      MARIADB_USER: InsideTest
      MARIADB_PASSWORD: insidetest
    volumes:
     - /var/lib/InsideTest/Db:/var/lib/mysql
    ports:
     - 8666:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8555:8080